#
# Executes commands at the start of an interactive session.
#

if [ "$COLORTERM" = "xfce4-terminal" ]; then
	export TERM=xterm-256color
fi

if [ "$TERM" = "linux" ]; then
		# 256-colour solarized
		echo -en "\e]P0073642" #black
		echo -en "\e]P1dc322f" #darkgrey
		echo -en "\e]P2859900" #darkred
		echo -en "\e]P3b58900" #red
		echo -en "\e]P4268bd2" #darkgreen
		echo -en "\e]P5d33682" #green
		echo -en "\e]P62aa198" #brown
		echo -en "\e]P7eee8d5" #yellow
		echo -en "\e]P8002b36" #darkblue
		echo -en "\e]P9cb4b16" #blue
		echo -en "\e]PA586e75" #darkmagenta
		echo -en "\e]PB657b83" #magenta
		echo -en "\e]PC839496" #darkcyan
		echo -en "\e]PD6c71c4" #cyan
		echo -en "\e]PE93a1a1" #lightgrey
		echo -en "\e]PFfdf6e3" #white
		clear #for background artifacting
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export EDITOR=vim
export VISUAL=vim
export PAGER=most
export LIBVIRT_DEFAULT_URI=qemu+ssh://darac@crush/system
setopt interactivecomments
stty -ixon	# Disable Ctrl+S/Ctrl+Q Flow Control

if [[ -s "/usr/share/powerline/binding/zsh/powerline.zsh" ]]; then
	source "/usr/share/powerline/bindings/zsh/powerline.zsh"
elif [[ -s "/home/darac/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh" ]]; then
	path+=/home/darac/.local/bin/
	export PATH
	if [[ -x /home/darac/.local/bin/powerline-client ]]; then
		export POWERLINE_COMMAND=powerline-client
	fi
	source "/home/darac/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh"
fi

## VirtualEnvWrapper stuff
if [[ -s "/etc/bash_completion.d/virtualenvwrapper" ]]; then
	export WORKON_HOME=$HOME/.virtualenvs
	if [[ ! -d $WORKON_HOME ]]; then
		mkdir -p $WORKON_HOME
	fi
	source "/etc/bash_completion.d/virtualenvwrapper"
fi

if [[ -x /usr/bin/keychain ]]; then
	eval $(/usr/bin/keychain -q --eval id_ecdsa id_rsa github_id_rsa CC9A6F67 --inherit any-once)
fi

if [[ -x /usr/bin/rbenv ]]; then
		eval "$(rbenv init -)"
fi
