#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

if [ "$COLORTERM" = "xfce4-terminal" ]; then
	export TERM=xterm-256color
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export EDITOR=vim
export VISUAL=vim
export PAGER=most
export ftp_proxy=http://winterwolf.co.uk:8080/
export http_proxy=http://winterwolf.co.uk:8080/
export https_proxy=http://winterwolf.co.uk:8080/
setopt interactivecomments

if [[ -s "/usr/share/powerline/bindings/zsh/powerline.zsh" ]]; then
	source "/usr/share/powerline/bindings/zsh/powerline.zsh" 
elif [[ -s "/home/darac/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh" ]]; then
	path+=/home/darac/.local/bin/
	export PATH
	if [[ -x /home/darac/.local/bin/powerline-client ]]; then
		export POWERLINE_COMMAND=powerline-client
	fi
	source "/home/darac/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh"
fi


if [[ -x /usr/bin/keychain ]]; then
	eval $(/usr/bin/keychain -q --eval id_rsa github_id_rsa CC9A6F67)
fi
